name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # to upload assets to releases
      attestations: write # to upload assets attestation for build provenance
      id-token: write # grant additional permission to attestation action to mint the OIDC token permission

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.22

    - name: Build
      run: |
        go get ./...
        go build -buildmode=c-shared -o pacman.so -v ./...

    - name: Upload Release Asset
      uses: softprops/action-gh-release@v2
      with:
        files: |
          pacman.so
